/********************************************************************
* IngridBasicReconSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error IngridBasicReconSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableIngridBasicReconSummaryDict();
extern void G__cpp_setup_inheritanceIngridBasicReconSummaryDict();
extern void G__cpp_setup_typetableIngridBasicReconSummaryDict();
extern void G__cpp_setup_memvarIngridBasicReconSummaryDict();
extern void G__cpp_setup_globalIngridBasicReconSummaryDict();
extern void G__cpp_setup_memfuncIngridBasicReconSummaryDict();
extern void G__cpp_setup_funcIngridBasicReconSummaryDict();
extern void G__set_cpp_environmentIngridBasicReconSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "IngridBasicReconSummary.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_TClass;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_TBuffer;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_TObject;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_TRef;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_IngridHitSummary;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_IngridTrackSummary;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_IngridBasicReconSummary;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__IngridBasicReconSummaryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
