/********************************************************************
* NeutInfoSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NeutInfoSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableNeutInfoSummaryDict();
extern void G__cpp_setup_inheritanceNeutInfoSummaryDict();
extern void G__cpp_setup_typetableNeutInfoSummaryDict();
extern void G__cpp_setup_memvarNeutInfoSummaryDict();
extern void G__cpp_setup_globalNeutInfoSummaryDict();
extern void G__cpp_setup_memfuncNeutInfoSummaryDict();
extern void G__cpp_setup_funcNeutInfoSummaryDict();
extern void G__set_cpp_environmentNeutInfoSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NeutInfoSummary.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NeutInfoSummaryDictLN_TClass;
extern G__linked_taginfo G__NeutInfoSummaryDictLN_TBuffer;
extern G__linked_taginfo G__NeutInfoSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__NeutInfoSummaryDictLN_TObject;
extern G__linked_taginfo G__NeutInfoSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NeutInfoSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NeutInfoSummaryDictLN_NeutInfoSummary;

/* STUB derived class for protected member access */
