/********************************************************************
* INGRIDEVENTSUMMARYDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error INGRIDEVENTSUMMARYDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableINGRIDEVENTSUMMARYDict();
extern void G__cpp_setup_inheritanceINGRIDEVENTSUMMARYDict();
extern void G__cpp_setup_typetableINGRIDEVENTSUMMARYDict();
extern void G__cpp_setup_memvarINGRIDEVENTSUMMARYDict();
extern void G__cpp_setup_globalINGRIDEVENTSUMMARYDict();
extern void G__cpp_setup_memfuncINGRIDEVENTSUMMARYDict();
extern void G__cpp_setup_funcINGRIDEVENTSUMMARYDict();
extern void G__set_cpp_environmentINGRIDEVENTSUMMARYDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "INGRIDEVENTSUMMARY.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_TClass;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_TBuffer;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_TMemberInspector;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_TObject;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_TClonesArray;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_IngridSimHitSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_IngridHitSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_IngridSimVertexSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_IngridSimParticleSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_BeamInfoSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_IngridTrackSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_IngridBasicReconSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_Ingrid1stReducSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_NeutInfoSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_PMReconSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_PMAnaSummary;
extern G__linked_taginfo G__INGRIDEVENTSUMMARYDictLN_IngridEventSummary;

/* STUB derived class for protected member access */
