/********************************************************************
* BeamInfoSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BeamInfoSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableBeamInfoSummaryDict();
extern void G__cpp_setup_inheritanceBeamInfoSummaryDict();
extern void G__cpp_setup_typetableBeamInfoSummaryDict();
extern void G__cpp_setup_memvarBeamInfoSummaryDict();
extern void G__cpp_setup_globalBeamInfoSummaryDict();
extern void G__cpp_setup_memfuncBeamInfoSummaryDict();
extern void G__cpp_setup_funcBeamInfoSummaryDict();
extern void G__set_cpp_environmentBeamInfoSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BeamInfoSummary.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BeamInfoSummaryDictLN_TClass;
extern G__linked_taginfo G__BeamInfoSummaryDictLN_TBuffer;
extern G__linked_taginfo G__BeamInfoSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__BeamInfoSummaryDictLN_TObject;
extern G__linked_taginfo G__BeamInfoSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BeamInfoSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BeamInfoSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BeamInfoSummaryDictLN_BeamInfoSummary;

/* STUB derived class for protected member access */
