/********************************************************************
* IngridSimHitSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error IngridSimHitSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableIngridSimHitSummaryDict();
extern void G__cpp_setup_inheritanceIngridSimHitSummaryDict();
extern void G__cpp_setup_typetableIngridSimHitSummaryDict();
extern void G__cpp_setup_memvarIngridSimHitSummaryDict();
extern void G__cpp_setup_globalIngridSimHitSummaryDict();
extern void G__cpp_setup_memfuncIngridSimHitSummaryDict();
extern void G__cpp_setup_funcIngridSimHitSummaryDict();
extern void G__set_cpp_environmentIngridSimHitSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "IngridSimHitSummary.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__IngridSimHitSummaryDictLN_TClass;
extern G__linked_taginfo G__IngridSimHitSummaryDictLN_TBuffer;
extern G__linked_taginfo G__IngridSimHitSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__IngridSimHitSummaryDictLN_TObject;
extern G__linked_taginfo G__IngridSimHitSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__IngridSimHitSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__IngridSimHitSummaryDictLN_IngridSimHitSummary;

/* STUB derived class for protected member access */
