/********************************************************************
* IngridTrackSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error IngridTrackSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableIngridTrackSummaryDict();
extern void G__cpp_setup_inheritanceIngridTrackSummaryDict();
extern void G__cpp_setup_typetableIngridTrackSummaryDict();
extern void G__cpp_setup_memvarIngridTrackSummaryDict();
extern void G__cpp_setup_globalIngridTrackSummaryDict();
extern void G__cpp_setup_memfuncIngridTrackSummaryDict();
extern void G__cpp_setup_funcIngridTrackSummaryDict();
extern void G__set_cpp_environmentIngridTrackSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "IngridTrackSummary.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__IngridTrackSummaryDictLN_TClass;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_TBuffer;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_TObject;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_TRef;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_IngridHitSummary;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_IngridSimParticleSummary;
extern G__linked_taginfo G__IngridTrackSummaryDictLN_IngridTrackSummary;

/* STUB derived class for protected member access */
