/********************************************************************
* Ingrid1stReducSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Ingrid1stReducSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableIngrid1stReducSummaryDict();
extern void G__cpp_setup_inheritanceIngrid1stReducSummaryDict();
extern void G__cpp_setup_typetableIngrid1stReducSummaryDict();
extern void G__cpp_setup_memvarIngrid1stReducSummaryDict();
extern void G__cpp_setup_globalIngrid1stReducSummaryDict();
extern void G__cpp_setup_memfuncIngrid1stReducSummaryDict();
extern void G__cpp_setup_funcIngrid1stReducSummaryDict();
extern void G__set_cpp_environmentIngrid1stReducSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Ingrid1stReducSummary.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_TClass;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_TBuffer;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_TObject;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_TRef;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_IngridHitSummary;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_Ingrid1stReducSummary;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__Ingrid1stReducSummaryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
