/********************************************************************
* PMAnaSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PMAnaSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablePMAnaSummaryDict();
extern void G__cpp_setup_inheritancePMAnaSummaryDict();
extern void G__cpp_setup_typetablePMAnaSummaryDict();
extern void G__cpp_setup_memvarPMAnaSummaryDict();
extern void G__cpp_setup_globalPMAnaSummaryDict();
extern void G__cpp_setup_memfuncPMAnaSummaryDict();
extern void G__cpp_setup_funcPMAnaSummaryDict();
extern void G__set_cpp_environmentPMAnaSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PMAnaSummary.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PMAnaSummaryDictLN_TClass;
extern G__linked_taginfo G__PMAnaSummaryDictLN_TBuffer;
extern G__linked_taginfo G__PMAnaSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__PMAnaSummaryDictLN_TObject;
extern G__linked_taginfo G__PMAnaSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__PMAnaSummaryDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__PMAnaSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PMAnaSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PMAnaSummaryDictLN_TRef;
extern G__linked_taginfo G__PMAnaSummaryDictLN_IngridHitSummary;
extern G__linked_taginfo G__PMAnaSummaryDictLN_IngridTrackSummary;
extern G__linked_taginfo G__PMAnaSummaryDictLN_PMAnaSummary;
extern G__linked_taginfo G__PMAnaSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__PMAnaSummaryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
