/********************************************************************
* IngridHitSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error IngridHitSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableIngridHitSummaryDict();
extern void G__cpp_setup_inheritanceIngridHitSummaryDict();
extern void G__cpp_setup_typetableIngridHitSummaryDict();
extern void G__cpp_setup_memvarIngridHitSummaryDict();
extern void G__cpp_setup_globalIngridHitSummaryDict();
extern void G__cpp_setup_memfuncIngridHitSummaryDict();
extern void G__cpp_setup_funcIngridHitSummaryDict();
extern void G__set_cpp_environmentIngridHitSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "IngridHitSummary.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__IngridHitSummaryDictLN_TClass;
extern G__linked_taginfo G__IngridHitSummaryDictLN_TBuffer;
extern G__linked_taginfo G__IngridHitSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__IngridHitSummaryDictLN_TObject;
extern G__linked_taginfo G__IngridHitSummaryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__IngridHitSummaryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__IngridHitSummaryDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__IngridHitSummaryDictLN_TRef;
extern G__linked_taginfo G__IngridHitSummaryDictLN_IngridSimHitSummary;
extern G__linked_taginfo G__IngridHitSummaryDictLN_IngridHitSummary;

/* STUB derived class for protected member access */
