/********************************************************************
* IngridSimParticleSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error IngridSimParticleSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableIngridSimParticleSummaryDict();
extern void G__cpp_setup_inheritanceIngridSimParticleSummaryDict();
extern void G__cpp_setup_typetableIngridSimParticleSummaryDict();
extern void G__cpp_setup_memvarIngridSimParticleSummaryDict();
extern void G__cpp_setup_globalIngridSimParticleSummaryDict();
extern void G__cpp_setup_memfuncIngridSimParticleSummaryDict();
extern void G__cpp_setup_funcIngridSimParticleSummaryDict();
extern void G__set_cpp_environmentIngridSimParticleSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "IngridSimParticleSummary.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__IngridSimParticleSummaryDictLN_TClass;
extern G__linked_taginfo G__IngridSimParticleSummaryDictLN_TBuffer;
extern G__linked_taginfo G__IngridSimParticleSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__IngridSimParticleSummaryDictLN_TObject;
extern G__linked_taginfo G__IngridSimParticleSummaryDictLN_IngridSimParticleSummary;

/* STUB derived class for protected member access */
