/********************************************************************
* IngridSimVertexSummaryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error IngridSimVertexSummaryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableIngridSimVertexSummaryDict();
extern void G__cpp_setup_inheritanceIngridSimVertexSummaryDict();
extern void G__cpp_setup_typetableIngridSimVertexSummaryDict();
extern void G__cpp_setup_memvarIngridSimVertexSummaryDict();
extern void G__cpp_setup_globalIngridSimVertexSummaryDict();
extern void G__cpp_setup_memfuncIngridSimVertexSummaryDict();
extern void G__cpp_setup_funcIngridSimVertexSummaryDict();
extern void G__set_cpp_environmentIngridSimVertexSummaryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "IngridSimVertexSummary.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__IngridSimVertexSummaryDictLN_TClass;
extern G__linked_taginfo G__IngridSimVertexSummaryDictLN_TBuffer;
extern G__linked_taginfo G__IngridSimVertexSummaryDictLN_TMemberInspector;
extern G__linked_taginfo G__IngridSimVertexSummaryDictLN_TObject;
extern G__linked_taginfo G__IngridSimVertexSummaryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__IngridSimVertexSummaryDictLN_IngridSimVertexSummary;
extern G__linked_taginfo G__IngridSimVertexSummaryDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__IngridSimVertexSummaryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
